sudo: required
services:
  - docker 

defore_install:
  - docekr build -t tanuj/docker-react - f Dockerfile.dev .

script:
  - docker run -e CI=true tanuj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-920247859827"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"